### ISSUE TITLE
stopped to working

### ISSUE THREAD

**Issue by murcin** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#19]
I think after updating to 2022.8 burze.dzis.net stopped to working... no entities shows up... all just gone and in logs there is something like this

```
2022-08-05 15:00:25.319 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up burze_dzis_net platform for binary_sensor
Traceback (most recent call last):
File "/config/custom_components/burze_dzis_net/binary_sensor.py", line 217, in _update_data
self.szukaj_burzy_output = service.szukaj_burzy(self._y, self._x, self._radius, self._api_key)
File "/usr/local/lib/python3.10/site-packages/zeep/proxy.py", line 46, in __call__
return self._proxy._binding.send(
File "/usr/local/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 135, in send
return self.process_reply(client, operation_obj, response)
File "/usr/local/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
return self.process_error(doc, operation)
File "/usr/local/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 329, in process_error
raise Fault(
zeep.exceptions.Fault: Nieprawidłowe współrzędne, dopuszczalne współrzędne w formie DM / Incorrect coordinates, acceptable coordinates in the form of DM.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/burze_dzis_net/binary_sensor.py", line 103, in async_setup_platform
await updater.async_update()
File "/config/custom_components/burze_dzis_net/binary_sensor.py", line 209, in _async_update
await self._hass.async_add_executor_job(self._update_data)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/burze_dzis_net/binary_sensor.py", line 219, in _update_data
_LOGGER.error('Error setting up burze_dzis_net: {}', fault)
File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
self._log(ERROR, msg, args, **kwargs)
File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
self.handle(record)
File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
self.callHandlers(record)
File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
hdlr.handle(record)
File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
self.emit(record)
File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 179, in emit
entry = LogEntry(
File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 96, in __init__
self.message = deque([record.getMessage()], maxlen=5)
File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by PiotrMachowski** [comment]
Can you show your config?

**Comment by murcin** [comment]
sure !
Instalation via HACS - no big deal and configuration as spited files in binary_sensor folder
![image](https://user-images.githubusercontent.com/66697668/183089960-dfb2960a-90d4-4a3d-8751-486f837bd031.png)

**Comment by Tomasz45** [comment]
A ja mam taki problem. Po wywołaniu alarmu mam takie info:
![image](https://user-images.githubusercontent.com/94935294/183252433-643d853c-c997-45d3-8d3d-d25136ba6be0.png)

**Comment by PiotrMachowski** [comment]
@Tomasz45  Co rozumiesz jako "wywołaniu"? Swoją drogą to jest błąd karty, nie integracji

**Comment by Tomasz45** [comment]
Wywołaniu stanu sensora on

**Comment by PiotrMachowski** [comment]
@Tomasz45 Rozumiem, że zmieniłeś ręcznie w dev toolsach? Taka zmiana nie wystarczy, bo oprócz zmiany stanu w sensorze pojawiają się atrybuty opisujące dane ostrzeżenie, z których zapewne ta karta korzysta

**Comment by Tomasz45** [comment]
Rozumiem, czyli trzeba czekać na info z API. Dziękuję

**Comment by murcin** [comment]
w moim przypadku kluczowe będzie zdanie w logach:
`Nieprawidłowe współrzędne, dopuszczalne współrzędne w formie DM `

jednak to nigdy nie było obowiązkowe... czy aktualnie coś się zmieniło? bo przynajmniej ja nic nie zmieniałem i zawsze działało :)

**Comment by PiotrMachowski** [comment]
Właśnie to jest dziwne, ale żeby to sprawdzić bym musiał mieć współrzędne Twojego domu :D możesz mi je gdzieś na priv wysłać?

**Comment by murcin** [comment]
pewnie :) wysyłam na priv - dodam że jak wpisałem  przybliżone dane wróciło do normy

`  latitude: xx.xx
  longitude: xx.xx`

**Comment by PiotrMachowski** [comment]
`piotr.machowski.dev [at] gmail.com`

**Comment by MarekLe** [comment]
Potwierdzam problem - taki sam błąd w logu jak kolega murcin powyżej wkleił.

**Comment by PiotrMachowski** [comment]
@MarekLe Czy jedna ze współrzędnych Twojego domu jest niewiele mniejsza niż wartość całkowita? (np 56.99234)

**Comment by Murcin86** [comment]
> Potwierdzam problem - taki sam błąd w logu jak kolega murcin powyżej wkleił.

Wrzuć w konfigurację długość u szerokość geograficzna gdzie będą max dwa miejsca ja po przecinku :)

**Comment by PiotrMachowski** [comment]
@Murcin86 a dokładniej problem istnieje gdy część ułamkowa jakiejś współrzędnej jest większa niż `0.9916666666666667`. Wtedy podanie `0.99` rozwiązuje problem

**Comment by MarekLe** [comment]
> @MarekLe Czy jedna ze współrzędnych Twojego domu jest niewiele mniejsza niż wartość całkowita? (np. `56.99234`)

Dokładnie, u mnie jedna ze współrzędnych miała po przecinku .997177. zaokrągliłem i teraz działa.

**Comment by PiotrMachowski** [comment]
Fixed in `v2.0.0`
